const quotes = [
  {
    name_en: 'Michael Jordan',
    name_he: 'מייקל ג\'ורדן',
    sport_en: 'Basketball',
    sport_he: 'כדורסל',
    quote_en: "I've missed more than 9,000 shots in my career. I've lost almost 300 games. Twenty-six times I've been trusted to take the game-winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.",
    quote_he: 'החטאתי יותר מ-9,000 זריקות בקריירה שלי. הפסדתי כמעט 300 משחקים. עשרים ושש פעמים סמכו עליי לזרוק את הזריקה המכרעת והחטאתי. נכשלתי שוב ושוב ושוב בחיים שלי. ובגלל זה אני מצליח.',
    bio_he: 'מייקל ג\'ורדן נחשב לשחקן הכדורסל הגדול בכל הזמנים. זכה בשישה אליפויות NBA עם שיקגו בולס והוכתר חמש פעמים כ-MVP של הליגה.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Michael_Jordan_in_2014.jpg/330px-Michael_Jordan_in_2014.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%9E%D7%99%D7%99%D7%A7%D7%9C_%D7%92%27%D7%95%D7%A8%D7%93%D7%9F',
  },
  {
    name_en: 'Muhammad Ali',
    name_he: 'מוחמד עלי',
    sport_en: 'Boxing',
    sport_he: 'אגרוף',
    quote_en: "He who is not courageous enough to take risks will accomplish nothing in life.",
    quote_he: 'מי שאינו אמיץ מספיק לקחת סיכונים לא ישיג דבר בחיים.',
    bio_he: 'מוחמד עלי היה מתאגרף אמריקאי, נחשב לאחד הספורטאים הגדולים והמשפיעים ביותר במאה ה-20. זכה באליפות העולם במשקל כבד שלוש פעמים.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Muhammad_Ali_NYWTS.jpg/330px-Muhammad_Ali_NYWTS.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%9E%D7%95%D7%97%D7%9E%D7%93_%D7%A2%D7%9C%D7%99_(%D7%9E%D7%AA%D7%90%D7%92%D7%A8%D7%A3)',
  },
  {
    name_en: 'Serena Williams',
    name_he: 'סרינה וויליאמס',
    sport_en: 'Tennis',
    sport_he: 'טניס',
    quote_en: "I really think a champion is defined not by their wins but by how they can recover when they fall.",
    quote_he: 'אני באמת חושבת שאלוף מוגדר לא לפי הניצחונות שלו, אלא לפי איך הוא מצליח להתאושש כשהוא נופל.',
    bio_he: 'סרינה וויליאמס היא טניסאית אמריקאית, בעלת 23 תארי גראנד סלאם בסינגלס. נחשבת לאחת הטניסאיות הגדולות בכל הזמנים.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Serena_Williams_at_the_2025_International_Tennis_Hall_of_Fame_Induction_Ceremony_Press_Conference_%28cropped%29.jpg/330px-Serena_Williams_at_the_2025_International_Tennis_Hall_of_Fame_Induction_Ceremony_Press_Conference_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A1%D7%A8%D7%99%D7%A0%D7%94_%D7%95%D7%99%D7%9C%D7%99%D7%90%D7%9E%D7%A1',
  },
  {
    name_en: 'Usain Bolt',
    name_he: 'יוסיין בולט',
    sport_en: 'Sprinting',
    sport_he: 'ריצות קצרות',
    quote_en: "Worrying gets you nowhere. If you turn up worrying about how you're going to perform, you've already lost. Train hard, turn up, run your best and the rest will take care of itself.",
    quote_he: 'דאגות לא מובילות לשום מקום. אם אתה מגיע מודאג, כבר הפסדת. תתאמן קשה, תעשה את המיטב, והשאר יסתדר מעצמו.',
    bio_he: 'יוסיין בולט הוא ספרינטר ג\'מייקני, מחזיק שיא העולם בריצת 100 מטר ו-200 מטר. זכה בשמונה מדליות זהב אולימפיות.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Usain_Bolt_-_240422_190142_%28cropped%29.jpg/330px-25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Usain_Bolt_-_240422_190142_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%99%D7%95%D7%A1%D7%99%D7%99%D7%9F_%D7%91%D7%95%D7%9C%D7%98',
  },
  {
    name_en: 'Pelé',
    name_he: 'פלה',
    sport_en: 'Soccer',
    sport_he: 'כדורגל',
    quote_en: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do.",
    quote_he: 'הצלחה היא לא מקרית. היא עבודה קשה, התמדה, למידה, הקרבה, ומעל הכל – אהבה למה שאתה עושה.',
    bio_he: 'פלה היה כדורגלן ברזילאי, נחשב לאחד הכדורגלנים הגדולים בכל הזמנים. זכה בשלושה גביעי עולם עם נבחרת ברזיל והבקיע למעלה מ-1,000 שערים בקריירה.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Pele_con_brasil_%28cropped%29.jpg/330px-Pele_con_brasil_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A4%D7%9C%D7%94',
  },
  {
    name_en: 'Lionel Messi',
    name_he: 'ליאונל מסי',
    sport_en: 'Soccer',
    sport_he: 'כדורגל',
    quote_en: "You have to fight to reach your dream. You have to sacrifice and work hard for it.",
    quote_he: 'אתה חייב להילחם כדי להגיע לחלום שלך. אתה חייב להקריב ולעבוד קשה למענו.',
    bio_he: 'ליאונל מסי הוא כדורגלן ארגנטינאי, זוכה שמונה פעמים בכדור הזהב. הוביל את ארגנטינה לזכייה בגביע העולם 2022 ונחשב לאחד הגדולים בהיסטוריה.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Lionel_Messi_NE_Revolution_Inter_Miami_7.9.25-178.jpg/330px-Lionel_Messi_NE_Revolution_Inter_Miami_7.9.25-178.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%9C%D7%99%D7%95%D7%A0%D7%9C_%D7%9E%D7%A1%D7%99',
  },
  {
    name_en: 'Cristiano Ronaldo',
    name_he: 'כריסטיאנו רונאלדו',
    sport_en: 'Soccer',
    sport_he: 'כדורגל',
    quote_en: "Talent without working hard is nothing.",
    quote_he: 'כישרון בלי עבודה קשה הוא כלום.',
    bio_he: 'כריסטיאנו רונאלדו הוא כדורגלן פורטוגלי, אחד מכובשי השערים הפוריים ביותר בהיסטוריה. זכה בחמישה כדורי זהב ובחמישה תארי ליגת האלופות.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Cristiano_Ronaldo_2275_%28cropped%29.jpg/330px-Cristiano_Ronaldo_2275_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%9B%D7%A8%D7%99%D7%A1%D7%98%D7%99%D7%90%D7%A0%D7%95_%D7%A8%D7%95%D7%A0%D7%90%D7%9C%D7%93%D7%95',
  },
  {
    name_en: 'Kobe Bryant',
    name_he: 'קובי בראיינט',
    sport_en: 'Basketball',
    sport_he: 'כדורסל',
    quote_en: "Everything negative – pressure, challenges – is all an opportunity for me to rise.",
    quote_he: 'כל דבר שלילי – לחץ, אתגרים – הכל הזדמנות בשבילי להתעלות.',
    bio_he: 'קובי בראיינט היה שחקן כדורסל אמריקאי שכיכב ב-NBA במשך 20 עונות עם לוס אנג\'לס לייקרס. זכה בחמישה תארי אליפות ונודע בזכות ה"מנטליות של הממבה".',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Kobe_Bryant_Dec_2014.jpg/330px-Kobe_Bryant_Dec_2014.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A7%D7%95%D7%91%D7%99_%D7%91%D7%A8%D7%90%D7%99%D7%99%D7%A0%D7%98',
  },
  {
    name_en: 'LeBron James',
    name_he: 'לברון ג\'יימס',
    sport_en: 'Basketball',
    sport_he: 'כדורסל',
    quote_en: "You can't be afraid to fail. It's the only way you succeed – you're not gonna succeed all the time, and I know that.",
    quote_he: 'אסור לך לפחד להיכשל. זו הדרך היחידה להצליח – אתה לא הולך להצליח כל הזמן, ואני יודע את זה.',
    bio_he: 'לברון ג\'יימס הוא שחקן כדורסל אמריקאי, מלך ההבקעות בהיסטוריה של ה-NBA. זכה בארבע אליפויות וארבעה תארי MVP.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/LeBron_James_%2851959977144%29_%28cropped2%29.jpg/330px-LeBron_James_%2851959977144%29_%28cropped2%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%9C%D7%91%D7%A8%D7%95%D7%9F_%D7%92%27%D7%99%D7%99%D7%9E%D7%A1',
  },
  {
    name_en: 'Wayne Gretzky',
    name_he: 'וויין גרצקי',
    sport_en: 'Ice Hockey',
    sport_he: 'הוקי קרח',
    quote_en: "You miss 100% of the shots you don't take.",
    quote_he: 'אתה מחמיץ 100% מההזדמנויות שאתה לא לוקח.',
    bio_he: 'וויין גרצקי הוא שחקן הוקי קרח קנדי, מכונה "הגדול". מחזיק במספר שיאים בלתי-ניתנים לשבירה ב-NHL ונחשב לשחקן הגדול בהיסטוריה של הוקי הקרח.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Andrew_Scheer_with_Wayne_Gretzky_%2848055697168%29_%28cropped%29.jpg/330px-Andrew_Scheer_with_Wayne_Gretzky_%2848055697168%29_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%95%D7%99%D7%99%D7%9F_%D7%92%D7%A8%D7%A6%D7%A7%D7%99',
  },
  {
    name_en: 'Mia Hamm',
    name_he: 'מיה האם',
    sport_en: 'Soccer',
    sport_he: 'כדורגל',
    quote_en: "The vision of a champion is bent over, drenched in sweat, at the point of exhaustion, when nobody else is looking.",
    quote_he: 'אלופה אמיתית היא מי שכפופה, ספוגה בזיעה, בנקודת התשישות – כשאף אחד לא מסתכל.',
    bio_he: 'מיה האם היא כדורגלנית אמריקאית לשעבר, נחשבת לאחת הכדורגלניות הטובות בהיסטוריה. זכתה פעמיים באליפות העולם לנשים ובשתי מדליות זהב אולימפיות.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Mia_Hamm_corner_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%9E%D7%99%D7%94_%D7%94%D7%90%D7%9D',
  },
  {
    name_en: 'Michael Phelps',
    name_he: 'מייקל פלפס',
    sport_en: 'Swimming',
    sport_he: 'שחייה',
    quote_en: "If you want to be the best, you have to do things that other people aren't willing to do.",
    quote_he: 'אם אתה רוצה להיות הכי טוב, אתה חייב לעשות דברים שאנשים אחרים לא מוכנים לעשות.',
    bio_he: 'מייקל פלפס הוא שחיין אמריקאי, הספורטאי המעוטר ביותר בהיסטוריה האולימפית עם 23 מדליות זהב. שלט בענפי השחייה במשך שני עשורים.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Michael_Phelps_Rio_Olympics_2016.jpg/330px-Michael_Phelps_Rio_Olympics_2016.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%9E%D7%99%D7%99%D7%A7%D7%9C_%D7%A4%D7%9C%D7%A4%D7%A1',
  },
  {
    name_en: 'Roger Federer',
    name_he: 'רוג\'ר פדרר',
    sport_en: 'Tennis',
    sport_he: 'טניס',
    quote_en: "Effortless is a myth. I had to work very hard to make it look easy.",
    quote_he: 'ללא מאמץ זה מיתוס. הייתי צריך לעבוד מאוד קשה כדי שזה ייראה קל.',
    bio_he: 'רוג\'ר פדרר הוא טניסאי שוויצרי, זוכה 20 תארי גראנד סלאם. נחשב לאחד הטניסאים הגדולים והאלגנטיים ביותר בהיסטוריה של המשחק.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Roger_Federer_2015_%28cropped%29.jpg/330px-Roger_Federer_2015_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A8%D7%95%D7%92%27%D7%A8_%D7%A4%D7%93%D7%A8%D7%A8',
  },
  {
    name_en: 'Billie Jean King',
    name_he: 'בילי ג\'ין קינג',
    sport_en: 'Tennis',
    sport_he: 'טניס',
    quote_en: "Pressure is a privilege. It only comes to those who earn it.",
    quote_he: 'לחץ הוא זכות. הוא מגיע רק למי שראוי לו.',
    bio_he: 'בילי ג\'ין קינג היא טניסאית אמריקאית לשעבר, זוכת 39 תארי גראנד סלאם. חלוצה במאבק לשוויון מגדרי בספורט וניצחה את בובי ריגס ב"קרב המינים".',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Billie_Jean_King_at_the_2026_Sundance_Film_Festival_02_%28crop_2%29.jpg/330px-Billie_Jean_King_at_the_2026_Sundance_Film_Festival_02_%28crop_2%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%91%D7%99%D7%9C%D7%99_%D7%92%27%D7%99%D7%9F_%D7%A7%D7%99%D7%A0%D7%92',
  },
  {
    name_en: 'Jackie Robinson',
    name_he: 'ג\'קי רובינסון',
    sport_en: 'Baseball',
    sport_he: 'בייסבול',
    quote_en: "A life is not important except in the impact it has on other lives.",
    quote_he: 'חיים אינם חשובים אלא בהשפעה שיש להם על חיי אחרים.',
    bio_he: 'ג\'קי רובינסון היה שחקן בייסבול אמריקאי, הראשון שפרץ את מחסום הצבע ב-MLB ב-1947. סלל את הדרך לדורות של ספורטאים שחורים בספורט האמריקאי.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Jackie_Robinson%2C_NPG_97_135.jpg/330px-Jackie_Robinson%2C_NPG_97_135.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%92%27%D7%A7%D7%99_%D7%A8%D7%95%D7%91%D7%99%D7%A0%D7%A1%D7%95%D7%9F',
  },
  {
    name_en: 'Nadia Comăneci',
    name_he: 'נדיה קומנצ\'י',
    sport_en: 'Gymnastics',
    sport_he: 'התעמלות',
    quote_en: "I don't run away from a challenge because I am afraid. Instead, I run toward it because the only way to escape fear is to trample it beneath your feet.",
    quote_he: 'אני לא בורחת מאתגר בגלל פחד. אני רצה לקראתו, כי הדרך היחידה להתגבר על פחד היא לדרוך עליו.',
    bio_he: 'נדיה קומנצ\'י היא מתעמלת רומנית, הראשונה בהיסטוריה שקיבלה ציון מושלם של 10 באולימפיאדה. זכתה בחמש מדליות זהב אולימפיות.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/25th_Laureus_World_Sports_Awards_-_Comaneci_-_240421_142851-2.jpg/330px-25th_Laureus_World_Sports_Awards_-_Comaneci_-_240421_142851-2.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A0%D7%93%D7%99%D7%94_%D7%A7%D7%95%D7%9E%D7%A0%D7%A5%27',
  },
  {
    name_en: 'Jesse Owens',
    name_he: 'ג\'סי אוונס',
    sport_en: 'Track and Field',
    sport_he: 'אתלטיקה קלה',
    quote_en: "We all have dreams. In order to make dreams come into reality, it takes an awful lot of determination, dedication, self-discipline, and effort.",
    quote_he: 'לכולנו יש חלומות. כדי להפוך חלומות למציאות, נדרשים המון נחישות, מסירות, משמעת עצמית ומאמץ.',
    bio_he: 'ג\'סי אוונס היה אתלט אמריקאי שזכה בארבע מדליות זהב באולימפיאדת ברלין 1936, תוך שהוא מפריך את תורת הגזע הנאצית.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Jesse_Owens_1936.jpg/330px-Jesse_Owens_1936.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%92%27%D7%A1%D7%99_%D7%90%D7%95%D7%95%D7%A0%D7%A1',
  },
  {
    name_en: 'Simone Biles',
    name_he: 'סימון ביילס',
    sport_en: 'Gymnastics',
    sport_he: 'התעמלות',
    quote_en: "I'd rather regret the risks that didn't work out than the chances I didn't take at all.",
    quote_he: 'אני מעדיפה להצטער על סיכונים שלא הצליחו מאשר על הזדמנויות שלא ניצלתי בכלל.',
    bio_he: 'סימון ביילס היא מתעמלת אמריקאית, המעוטרת ביותר בהיסטוריה של ההתעמלות האמנותית. זכתה בשבע מדליות אולימפיות, בהן ארבע מדליות זהב.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Simone_Biles_National_Team_2024.jpg/330px-Simone_Biles_National_Team_2024.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A1%D7%99%D7%9E%D7%95%D7%9F_%D7%91%D7%99%D7%99%D7%9C%D7%A1',
  },
  {
    name_en: 'Rafael Nadal',
    name_he: 'רפאל נדאל',
    sport_en: 'Tennis',
    sport_he: 'טניס',
    quote_en: "The glory is being happy. The glory is not winning here or winning there. The glory is enjoying practicing, enjoy every day, enjoying to work hard, trying to be a better player than before.",
    quote_he: 'הגדולה האמיתית היא להיות מאושר. לא לנצח פה או שם, אלא ליהנות מהאימונים, מכל יום, מעבודה קשה – לנסות להיות טוב יותר ממה שהיית.',
    bio_he: 'רפאל נדאל הוא טניסאי ספרדי, זוכה 22 תארי גראנד סלאם. מכונה "מלך החימר" בזכות שליטתו חסרת התקדים על מגרשי החימר.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Rafael_Nadal_en_2024_%28cropped%29.jpg/330px-Rafael_Nadal_en_2024_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A8%D7%A4%D7%90%D7%9C_%D7%A0%D7%93%D7%90%D7%9C',
  },
  {
    name_en: 'Novak Djokovic',
    name_he: 'נובאק ג\'וקוביץ\'',
    sport_en: 'Tennis',
    sport_he: 'טניס',
    quote_en: "You have to believe in yourself when nobody else will.",
    quote_he: 'אתה חייב להאמין בעצמך גם כשאף אחד אחר לא מאמין בך.',
    bio_he: 'נובאק ג\'וקוביץ\' הוא טניסאי סרבי, מחזיק שיא של 24 תארי גראנד סלאם. נחשב לאחד משלושת הגדולים בהיסטוריה של הטניס.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Novak_Djokovic_2024_Paris_Olympics.jpg/330px-Novak_Djokovic_2024_Paris_Olympics.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A0%D7%95%D7%91%D7%90%D7%A7_%D7%92%27%D7%95%D7%A7%D7%95%D7%91%D7%99%D7%A5%27',
  },
  {
    name_en: 'Tom Brady',
    name_he: 'טום בריידי',
    sport_en: 'American Football',
    sport_he: 'פוטבול אמריקאי',
    quote_en: "If you don't believe in yourself, why is anyone else going to believe in you?",
    quote_he: 'אם אתה לא מאמין בעצמך, למה שמישהו אחר יאמין בך?',
    bio_he: 'טום בריידי הוא שחקן פוטבול אמריקאי לשעבר, זוכה שבעה טבעות סופרבול. נחשב לקוורטרבק הגדול בהיסטוריה של ה-NFL.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Tom_Brady_-_240422_191334_%28cropped%29_%28cropped%29.jpg/330px-25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Tom_Brady_-_240422_191334_%28cropped%29_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%98%D7%95%D7%9D_%D7%91%D7%A8%D7%99%D7%99%D7%93%D7%99',
  },
  {
    name_en: 'Megan Rapinoe',
    name_he: 'מייגן רפינו',
    sport_en: 'Soccer',
    sport_he: 'כדורגל',
    quote_en: "Putting yourself out there is hard, but it's so worth it. Not only to other people, but to yourself.",
    quote_he: 'לחשוף את עצמך זה קשה, אבל זה כל כך שווה את זה. לא רק עבור אחרים, אלא עבור עצמך.',
    bio_he: 'מייגן רפינו היא כדורגלנית אמריקאית לשעבר, זוכת גביע העולם לנשים פעמיים. ידועה גם כפעילה חברתית ואייקון של שוויון בספורט.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Megan_Rapinoe_%2848675274817%29_%28cropped%29.jpg/330px-Megan_Rapinoe_%2848675274817%29_%28cropped%29.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Megan_Rapinoe',
  },
  {
    name_en: 'Derek Jeter',
    name_he: 'דרק ג\'יטר',
    sport_en: 'Baseball',
    sport_he: 'בייסבול',
    quote_en: "There may be people that have more talent than you, but there's no excuse for anyone to work harder than you do.",
    quote_he: 'אולי יש אנשים עם יותר כישרון ממך, אבל אין שום תירוץ שמישהו יעבוד קשה יותר ממך.',
    bio_he: 'דרק ג\'יטר הוא שחקן בייסבול אמריקאי לשעבר, קפטן ניו יורק יאנקיז במשך 12 שנים. זכה בחמישה תארי סדרה עולמית ונבחר לאולם התהילה.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Derek_Jeter_during_MLB_on_Fox_pre-game_show%2C_October_16%2C_2024_-_001_%28cropped%29.jpg/330px-Derek_Jeter_during_MLB_on_Fox_pre-game_show%2C_October_16%2C_2024_-_001_%28cropped%29.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Derek_Jeter',
  },
  {
    name_en: 'Venus Williams',
    name_he: 'ונוס וויליאמס',
    sport_en: 'Tennis',
    sport_he: 'טניס',
    quote_en: "You have to believe in yourself when no one else does – that makes you a winner right there.",
    quote_he: 'תאמינו בעצמכם כשאף אחד אחר לא מאמין – זה מה שהופך אתכם למנצחים.',
    bio_he: 'ונוס וויליאמס היא טניסאית אמריקאית, זוכת שבעה תארי גראנד סלאם בסינגלס. חלוצה בקידום שוויון התגמול בין נשים לגברים בטניס.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Venus_Williams_%282025_DC_Open%29_crop.jpg/330px-Venus_Williams_%282025_DC_Open%29_crop.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%95%D7%A0%D7%95%D7%A1_%D7%95%D7%99%D7%9C%D7%99%D7%90%D7%9E%D7%A1',
  },
  {
    name_en: 'Tiger Woods',
    name_he: 'טייגר וודס',
    sport_en: 'Golf',
    sport_he: 'גולף',
    quote_en: "The greatest thing about tomorrow is, I will be better than I am today.",
    quote_he: 'הדבר הכי נפלא במחר הוא שאהיה טוב יותר ממה שאני היום.',
    bio_he: 'טייגר וודס הוא גולפיסט אמריקאי, אחד הגדולים בהיסטוריה של הגולף. זכה ב-15 טורנירי מייג\'ור וב-82 טורנירים בסבב ה-PGA.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/President_Donald_Trump_hosts_a_reception_honoring_Black_History_Month_%2854341713089%29_%28cropped%29.jpg/330px-President_Donald_Trump_hosts_a_reception_honoring_Black_History_Month_%2854341713089%29_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%98%D7%99%D7%99%D7%92%D7%A8_%D7%95%D7%95%D7%93%D7%A1',
  },
  {
    name_en: 'David Beckham',
    name_he: 'דייוויד בקהאם',
    sport_en: 'Soccer',
    sport_he: 'כדורגל',
    quote_en: "I never do anything half-heartedly. I will continue to work hard and play hard and do everything I can to be successful, whatever I do.",
    quote_he: 'אני אף פעם לא עושה דברים בחצי לב. אמשיך לעבוד קשה ולעשות הכל כדי להצליח, בכל מה שאעשה.',
    bio_he: 'דייוויד בקהאם הוא כדורגלן אנגלי לשעבר, ידוע בבעיטות החופשיות המדויקות שלו. שיחק במנצ\'סטר יונייטד, ריאל מדריד ונבחרת אנגליה.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/David_Beckham_UNICEF_%28cropped2%29.jpg/330px-David_Beckham_UNICEF_%28cropped2%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%93%D7%99%D7%99%D7%95%D7%95%D7%99%D7%93_%D7%91%D7%A7%D7%94%D7%90%D7%9D',
  },
  {
    name_en: 'Sachin Tendulkar',
    name_he: 'סאצ\'ין טנדולקר',
    sport_en: 'Cricket',
    sport_he: 'קריקט',
    quote_en: "People throw stones at you and you convert them into milestones.",
    quote_he: 'אנשים זורקים עליך אבנים ואתה הופך אותן לאבני דרך.',
    bio_he: 'סאצ\'ין טנדולקר הוא קריקטאי הודי לשעבר, נחשב לאחד הגדולים בהיסטוריה של הקריקט. שיחק 24 שנים בנבחרת הודו ושבר אינספור שיאים.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/The_cricket_legend_Sachin_Tendulkar_at_the_Oval_Maidan_in_Mumbai_During_the_Duke_and_Duchess_of_Cambridge_Visit%2826271019082%29.jpg/330px-The_cricket_legend_Sachin_Tendulkar_at_the_Oval_Maidan_in_Mumbai_During_the_Duke_and_Duchess_of_Cambridge_Visit%2826271019082%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A1%D7%90%D7%A6%27%D7%99%D7%9F_%D7%98%D7%A0%D7%93%D7%95%D7%9C%D7%A7%D7%A8',
  },
  {
    name_en: 'Neymar Jr',
    name_he: 'ניימאר ג\'וניור',
    sport_en: 'Soccer',
    sport_he: 'כדורגל',
    quote_en: "The secret is to believe in your dreams; in your potential that you can be like your star, keep searching, keep believing and don't lose faith in yourself.",
    quote_he: 'הסוד הוא להאמין בחלומות שלך ובפוטנציאל שלך. תמשיך לחפש, תמשיך להאמין, ואל תאבד אמונה בעצמך.',
    bio_he: 'ניימאר ג\'וניור הוא כדורגלן ברזילאי, אחד השחקנים המוכשרים ביותר בדורו. כיכב בברצלונה ופריז סן-ז\'רמן ונחשב לאייקון של הכדורגל הברזילאי.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Neymar_Jr._with_Al_Hilal%2C_3_October_2023_-_03_%28cropped%29.jpg/330px-Neymar_Jr._with_Al_Hilal%2C_3_October_2023_-_03_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A0%D7%99%D7%99%D7%9E%D7%90%D7%A8',
  },
  {
    name_en: 'Lewis Hamilton',
    name_he: 'לואיס המילטון',
    sport_en: 'Formula 1',
    sport_he: 'פורמולה 1',
    quote_en: "I feel like people are expecting me to fail; therefore, I expect myself to win.",
    quote_he: 'אני מרגיש שאנשים מצפים ממני להיכשל; ולכן, אני מצפה מעצמי לנצח.',
    bio_he: 'לואיס המילטון הוא נהג פורמולה 1 בריטי, שבע פעמים אלוף עולם. מחזיק בשיאי ניצחונות רבים ונחשב לאחד הנהגים הגדולים בהיסטוריה של הספורט.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Prime_Minister_Keir_Starmer_meets_Sir_Lewis_Hamilton_%2854566928382%29_%28cropped%29.jpg/330px-Prime_Minister_Keir_Starmer_meets_Sir_Lewis_Hamilton_%2854566928382%29_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%9C%D7%95%D7%90%D7%99%D7%A1_%D7%94%D7%9E%D7%99%D7%9C%D7%98%D7%95%D7%9F',
  },
  {
    name_en: 'Zlatan Ibrahimović',
    name_he: 'זלאטן איברהימוביץ\'',
    sport_en: 'Soccer',
    sport_he: 'כדורגל',
    quote_en: "When people criticize me, instead of putting my head down, it gives me energy to do even more.",
    quote_he: 'כשאנשים מבקרים אותי, במקום להוריד את הראש, זה נותן לי אנרגיה לעשות עוד יותר.',
    bio_he: 'זלאטן איברהימוביץ\' הוא כדורגלן שוודי לשעבר, ידוע בשערים האקרובטיים שלו ובאישיות הצבעונית. שיחק בקבוצות המובילות באירופה כולל אינטר, ברצלונה ופריז סן-ז\'רמן.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Zlatan_Ibrahimovi%C4%87_June_2018.jpg/330px-Zlatan_Ibrahimovi%C4%87_June_2018.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%96%D7%9C%D7%90%D7%98%D7%9F_%D7%90%D7%99%D7%91%D7%A8%D7%94%D7%99%D7%9E%D7%95%D7%91%D7%99%D7%A5%27',
  },
  {
    name_en: 'Maria Sharapova',
    name_he: 'מריה שראפובה',
    sport_en: 'Tennis',
    sport_he: 'טניס',
    quote_en: "In order to be the best, you have to go through things that people don't understand.",
    quote_he: 'כדי להיות הכי טובה, את חייבת לעבור דברים שאנשים לא מבינים.',
    bio_he: 'מריה שראפובה היא טניסאית רוסית לשעבר, זוכת חמישה תארי גראנד סלאם. הפכה למספר 1 בעולם בגיל 18 והייתה מהספורטאיות המפורסמות בעולם.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Maria_Sharapova_during_opening_night_of_Web_Summit_2025_at_the_MEO_Arena_in_Lisbon%2C_Portugal.jpg/330px-Maria_Sharapova_during_opening_night_of_Web_Summit_2025_at_the_MEO_Arena_in_Lisbon%2C_Portugal.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%9E%D7%A8%D7%99%D7%94_%D7%A9%D7%A8%D7%A4%D7%95%D7%91%D7%94',
  },
  {
    name_en: 'Magic Johnson',
    name_he: 'מג\'יק ג\'ונסון',
    sport_en: 'Basketball',
    sport_he: 'כדורסל',
    quote_en: "In life, winning and losing will both happen. What is never acceptable is quitting.",
    quote_he: 'בחיים, גם ניצחונות וגם הפסדים יקרו. הדבר היחיד שאסור לעולם – זה לוותר.',
    bio_he: 'מג\'יק ג\'ונסון הוא שחקן כדורסל אמריקאי לשעבר, אחד הפלייסמייקרים הגדולים בהיסטוריה. זכה בחמש אליפויות NBA עם לוס אנג\'לס לייקרס.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Magic_Johnson_at_SXSW_2022_%2851958828669%29_%28cropped%29.jpg/330px-Magic_Johnson_at_SXSW_2022_%2851958828669%29_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%9E%D7%92%27%D7%99%D7%A7_%D7%92%27%D7%95%D7%A0%D7%A1%D7%95%D7%9F',
  },
  {
    name_en: 'Arthur Ashe',
    name_he: 'ארתור אש',
    sport_en: 'Tennis',
    sport_he: 'טניס',
    quote_en: "Start where you are. Use what you have. Do what you can.",
    quote_he: 'התחל מאיפה שאתה. השתמש במה שיש לך. עשה מה שאתה יכול.',
    bio_he: 'ארתור אש היה טניסאי אמריקאי, השחקן השחור הראשון שזכה בתואר גראנד סלאם. פעיל זכויות אדם שנאבק נגד אפרטהייד ולמען שוויון.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Arthur_Ashe_%28cropped%29.jpg/330px-Arthur_Ashe_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%90%D7%A8%D7%AA%D7%95%D7%A8_%D7%90%D7%A9',
  },
  {
    name_en: 'Babe Ruth',
    name_he: 'בייב רות\'',
    sport_en: 'Baseball',
    sport_he: 'בייסבול',
    quote_en: "Every strike brings me closer to the next home run.",
    quote_he: 'כל סטרייק מקרב אותי להומראן הבא.',
    bio_he: 'בייב רות\' היה שחקן בייסבול אמריקאי, מהגדולים והמשפיעים ביותר בהיסטוריה של הספורט. שיא ההומראנים שלו עמד במשך עשרות שנים.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Babe_Ruth2.jpg/330px-Babe_Ruth2.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%91%D7%99%D7%99%D7%91_%D7%A8%D7%95%D7%AA%27',
  },
  {
    name_en: 'Vince Lombardi',
    name_he: 'וינס לומברדי',
    sport_en: 'American Football (Coach)',
    sport_he: 'מאמן פוטבול אמריקאי',
    quote_en: "Perfection is not attainable, but if we chase perfection we can catch excellence.",
    quote_he: 'שלמות אי אפשר להשיג, אבל אם נרדוף אחריה – נוכל לתפוס מצוינות.',
    bio_he: 'וינס לומברדי היה מאמן פוטבול אמריקאי אגדי, שהוביל את גרין ביי פקרס לזכייה בחמישה תארי NFL. גביע הסופרבול נקרא על שמו.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Vince_Lombardi_%281913-1970%29_in_1964_Crop.jpg/330px-Vince_Lombardi_%281913-1970%29_in_1964_Crop.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%95%D7%99%D7%A0%D7%A1_%D7%9C%D7%95%D7%9E%D7%91%D7%A8%D7%93%D7%99',
  },
  {
    name_en: 'Michael Schumacher',
    name_he: 'מיכאל שומאכר',
    sport_en: 'Formula 1',
    sport_he: 'פורמולה 1',
    quote_en: "Once something is a passion, the motivation is there.",
    quote_he: 'ברגע שמשהו הוא תשוקה, המוטיבציה כבר שם.',
    bio_he: 'מיכאל שומאכר הוא נהג פורמולה 1 גרמני, שבע פעמים אלוף עולם. נחשב לאחד הנהגים הגדולים והמוצלחים ביותר בהיסטוריה של מרוצי המכוניות.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Michael_Schumacher_china_2012_rotated.png/330px-Michael_Schumacher_china_2012_rotated.png',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%9E%D7%99%D7%9B%D7%90%D7%9C_%D7%A9%D7%95%D7%9E%D7%90%D7%9B%D7%A8',
  },
  {
    name_en: 'Carl Lewis',
    name_he: 'קרל לואיס',
    sport_en: 'Track and Field',
    sport_he: 'אתלטיקה קלה',
    quote_en: "If you don't have confidence, you'll always find a way not to win.",
    quote_he: 'אם אין לך ביטחון עצמי, תמיד תמצא סיבה לא לנצח.',
    bio_he: 'קרל לואיס הוא אתלט אמריקאי, זוכה תשע מדליות זהב אולימפיות בריצות קצרות וקפיצה לרוחק. נחשב לאחד האתלטים הגדולים של המאה ה-20.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Carl_Lewis_%28cropped%29.jpg/330px-Carl_Lewis_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A7%D7%A8%D7%9C_%D7%9C%D7%95%D7%90%D7%99%D7%A1',
  },
  {
    name_en: 'Naomi Osaka',
    name_he: 'נאומי אוסקה',
    sport_en: 'Tennis',
    sport_he: 'טניס',
    quote_en: "You just gotta keep going and fighting for everything, and one day you'll get to where you want.",
    quote_he: 'את פשוט חייבת להמשיך ולהילחם על הכל, ויום אחד תגיעי למקום שאת רוצה.',
    bio_he: 'נאומי אוסקה היא טניסאית יפנית-אמריקאית, זוכת ארבעה תארי גראנד סלאם. הייתה הטניסאית הראשונה מאסיה שהגיעה לדירוג מספר 1 בעולם.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/NaomiOsaka-smile-2020_%28cropped_tight%29.png/330px-NaomiOsaka-smile-2020_%28cropped_tight%29.png',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A0%D7%90%D7%95%D7%9E%D7%99_%D7%90%D7%95%D7%A1%D7%A7%D7%94',
  },
  {
    name_en: 'Stephen Curry',
    name_he: 'סטפן קרי',
    sport_en: 'Basketball',
    sport_he: 'כדורסל',
    quote_en: "Success is not an accident, success is actually a choice.",
    quote_he: 'הצלחה היא לא מקרה, הצלחה היא בעצם בחירה.',
    bio_he: 'סטפן קרי הוא שחקן כדורסל אמריקאי, נחשב לקלעי השלש הגדול בהיסטוריה של ה-NBA. זכה בארבע אליפויות עם גולדן סטייט ווריורס.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Steph_Curry_P20230117AS-1347_%28cropped%29.jpg/330px-Steph_Curry_P20230117AS-1347_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%A1%D7%98%D7%A4%D7%9F_%D7%A7%D7%A8%D7%99',
  },
  {
    name_en: 'Thierry Henry',
    name_he: 'טיירי אנרי',
    sport_en: 'Soccer',
    sport_he: 'כדורגל',
    quote_en: "I always think about what I missed, and I think that was my driving force – never be satisfied with what I've done.",
    quote_he: 'אני תמיד חושב על מה שהחמצתי, וזה הכוח המניע שלי – לעולם לא להסתפק במה שהשגתי.',
    bio_he: 'טיירי אנרי הוא כדורגלן צרפתי לשעבר, מלך השערים בהיסטוריה של ארסנל. זכה בגביע העולם 1998 ובאליפות אירופה 2000 עם נבחרת צרפת.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Thierry_Henry_%2851649035951%29_%28cropped%29.jpg/330px-Thierry_Henry_%2851649035951%29_%28cropped%29.jpg',
    wikipedia: 'https://he.wikipedia.org/wiki/%D7%98%D7%99%D7%99%D7%A8%D7%99_%D7%90%D7%A0%D7%A8%D7%99',
  },
];

module.exports = { quotes };
